version: "2.4"
services:
  backend:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:7070
    volumes:
      - ./code:/code:ro
    read_only: true
    pids_limit: 256
    mem_limit: 512M
    cpus: 0.25
