version: "2.4"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1337:1337
    volumes:
      - ./app:/app:ro
    read_only: true
    pids_limit: 256
    mem_limit: 512M
    cpus: 0.25